name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 'Build ğŸ§±'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup ğŸ‘¨ğŸ»â€ğŸ’»
        uses: ./.github/actions/setup
        with:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Application ğŸ§±
        run: bun run build
        env:
          DATABASE_URL: url
          AUTH_DISCORD_ID: secret
          AUTH_DISCORD_SECRET: secret
          AUTH_GITHUB_ID: secret
          AUTH_GITHUB_SECRET: secret
          AUTH_SECRET: secret

      - name: Upload production artifact ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./.next

  lint:
    name: 'Lint ğŸ±'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup ğŸ‘¨ğŸ»â€ğŸ’»
        uses: ./.github/actions/setup
        with:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Lint JS files ğŸ±
        run: bun run lint
        env:
          DATABASE_URL: url
          AUTH_DISCORD_ID: secret
          AUTH_DISCORD_SECRET: secret
          AUTH_GITHUB_ID: secret
          AUTH_GITHUB_SECRET: secret
          AUTH_SECRET: secret

  test:
    name: 'Unit Tests ğŸ§ª'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup ğŸ‘¨ğŸ»â€ğŸ’»
        uses: ./.github/actions/setup
        with:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run unit tests ğŸ§ª
        run: bun run test:coverage

      - name: Collect coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    name: 'E2E Tests ğŸ§ª'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup ğŸ‘¨ğŸ»â€ğŸ’»
        uses: ./.github/actions/setup
        with:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Download production artifact ğŸ“¤
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./.next

      - name: log dist
        run: ls

      - name: Run e2e tests ğŸ§ª
        run: npx playwright test
        env:
          DATABASE_URL: url
          AUTH_DISCORD_ID: secret
          AUTH_DISCORD_SECRET: secret
          AUTH_GITHUB_ID: secret
          AUTH_GITHUB_SECRET: secret
          AUTH_SECRET: secret
          E2E_ACCOUNT_EMAIL: ${{ secrets.E2E_ACCOUNT_EMAIL }}
          E2E_ACCOUNT_PASSWORD: ${{ secrets.E2E_ACCOUNT_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
